#ifndef OSLAB_DISK_H
#define OSLAB_DISK_H
/* 固定偏移的 12 个小端 u32；禁止序列化宿主结构体。 */
#define FS_MAGIC (0x12341234)
#define BLOCK_SIZE (4096)
#define DISK_INODE_SIZE (64)
#define N_INODE (65536)
#define N_DATA_BLOCK (1310720)
#define INODE_BITMAP_FIRST (1)
#define INODE_BITMAP_BLOCKS ((N_INODE + BLOCK_SIZE * 8 - 1) / (BLOCK_SIZE * 8))
#define INODE_FIRST (INODE_BITMAP_FIRST + INODE_BITMAP_BLOCKS)
#define INODE_BLOCKS ((N_INODE * DISK_INODE_SIZE + BLOCK_SIZE - 1) / BLOCK_SIZE)
#define DATA_BITMAP_FIRST (INODE_FIRST + INODE_BLOCKS)
#define DATA_BITMAP_BLOCKS ((N_DATA_BLOCK + BLOCK_SIZE * 8 - 1) / (BLOCK_SIZE * 8))
#define DATA_FIRST (DATA_BITMAP_FIRST + DATA_BITMAP_BLOCKS)
#define TOTAL_BLOCKS (DATA_FIRST + N_DATA_BLOCK)
#define ROOT_INODE 0
#define INVALID_INODE_NUM 0xffffffffU
#define INODE_TYPE_DATA 0
#define INODE_TYPE_DIR 1
#define INODE_TYPE_DEVICE 2
#define INODE_MAJOR_DEFAULT 1
#define INODE_MINOR_DEFAULT 1
#define MAXLEN_FILENAME 60
#define INODE_INDEX_1 10
#define INODE_INDEX_2 12
#define INODE_INDEX_3 13
/* 各级逻辑块的排他边界；size 仍受 u32 上限限制。 */
#define INODE_BLOCK_INDEX_1 10
#define INODE_BLOCK_INDEX_2 (10 + 2048)
#define INODE_BLOCK_INDEX_3 (10 + 2048 + 1024 * 1024)
#define INODE_MAX_SIZE 0xffffffffU
#define INODE_PER_BLOCK (BLOCK_SIZE / DISK_INODE_SIZE)
#define DENTRY_PER_BLOCK (BLOCK_SIZE / 64)
#endif
