#ifndef OSLAB_DISK_H
#define OSLAB_DISK_H
/* 固定偏移的 12 个小端 u32；禁止序列化宿主结构体。 */
#define FS_MAGIC (0x12341234)
#define BLOCK_SIZE (4096)
#define DISK_INODE_SIZE (64)
#define N_INODE (65536)
#define N_DATA_BLOCK (1310720)
#define INODE_BITMAP_FIRST (1)
#define INODE_BITMAP_BLOCKS ((N_INODE + BLOCK_SIZE * 8 - 1) / (BLOCK_SIZE * 8))
#define INODE_FIRST (INODE_BITMAP_FIRST + INODE_BITMAP_BLOCKS)
#define INODE_BLOCKS ((N_INODE * DISK_INODE_SIZE + BLOCK_SIZE - 1) / BLOCK_SIZE)
#define DATA_BITMAP_FIRST (INODE_FIRST + INODE_BLOCKS)
#define DATA_BITMAP_BLOCKS ((N_DATA_BLOCK + BLOCK_SIZE * 8 - 1) / (BLOCK_SIZE * 8))
#define DATA_FIRST (DATA_BITMAP_FIRST + DATA_BITMAP_BLOCKS)
#define TOTAL_BLOCKS (DATA_FIRST + N_DATA_BLOCK)
#endif
